name: quantum-nifty-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit
  - scikit-learn
  - joblib
  - yfinance
  - pandas
  - plotly
  - pip
  - pip:
    - qiskit==0.46.0
    - qiskit-machine-learning==0.7.2
    - qiskit-aer==0.13.3
